export const clerkAuthAppearance = {
  variables: {
    colorPrimary: "#1f62c8",
    colorBackground: "#f8fbff",
    colorInputBackground: "#ffffff",
    colorInputText: "#1e2f48",
    colorText: "#1e2f48",
    colorTextSecondary: "#526b8f",
    colorDanger: "#c4453f",
    borderRadius: "16px",
    fontFamily: "var(--font-manrope), 'Segoe UI', sans-serif",
  },
  elements: {
    rootBox: "auth-root-box",
    cardBox: "auth-card-box",
    card: "auth-card",
    headerTitle: "auth-title",
    headerSubtitle: "auth-subtitle",
    socialButtonsBlockButton: "auth-social-button",
    socialButtonsBlockButtonText: "auth-social-button-text",
    dividerLine: "auth-divider-line",
    dividerText: "auth-divider-text",
    formFieldLabel: "auth-field-label",
    formFieldInput: "auth-input",
    formButtonPrimary: "auth-primary-button",
    footerActionText: "auth-footer-text",
    footerActionLink: "auth-footer-link",
    alert: "auth-alert",
    formFieldErrorText: "auth-error-text",
    identityPreviewText: "auth-identity-preview",
  },
} as const;
